# This workflow builds the Python package, and uploads to PyPI using Twine

name: Build & upload to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install wheel publishing deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade twine build
      - name: Build wheels and sdist
        run: |
          python -m build
      - env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload ./dist/*.whl ./dist/*.tar.gz
